# Generated by Django 3.0.3 on 2020-06-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userActivityApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='regno',
            new_name='reg_id',
        ),
    ]
